package com.altria.dialog.constant;

public class EricssonHeaderConstant {
    public static final String EVENT_HEADER_4114_PROC_ERAB_RELEASE = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference,triggeringNode,s1ReleaseCause," +
            "internalReleaseCause,erabReleaseResult," +
            "erabDataLost_0,erabDataLost_1,erabDataLost_2,erabDataLost_3," +
            "erabDataLost_4,erabDataLost_5,erabDataLost_6,erabDataLost_7," +
            "erabDataLost_8,erabDataLost_9,erabDataLost_10,erabDataLost_11," +
            "erabDataLost_12,erabDataLost_13,erabDataLost_14,erabDataLost_15," +
            "erabReleaseReqQci_0,erabReleaseReqQci_1,erabReleaseReqQci_2,erabReleaseReqQci_3," +
            "erabReleaseReqQci_4,erabReleaseReqQci_5,erabReleaseReqQci_6,erabReleaseReqQci_7," +
            "erabReleaseReqQci_8,erabReleaseReqQci_9,erabReleaseReqQci_10,erabReleaseReqQci_11," +
            "erabReleaseReqQci_12,erabReleaseReqQci_13,erabReleaseReqQci_14,erabReleaseReqQci_15," +
            "erabReleaseReqBitmap,erabReleaseReq" +
            "erabReleaseReq3gppCauseGroup_0,erabReleaseReq3gppCauseGroup_1," +
            "erabReleaseReq3gppCauseGroup_2,erabReleaseReq3gppCauseGroup_3," +
            "erabReleaseReq3gppCauseGroup_4,erabReleaseReq3gppCauseGroup_5," +
            "erabReleaseReq3gppCauseGroup_6,erabReleaseReq3gppCauseGroup_7," +
            "erabReleaseReq3gppCauseGroup_8,erabReleaseReq3gppCauseGroup_9," +
            "erabReleaseReq3gppCauseGroup_10,erabReleaseReq3gppCauseGroup_11," +
            "erabReleaseReq3gppCauseGroup_12,erabReleaseReq3gppCauseGroup_13," +
            "erabReleaseReq3gppCauseGroup_14,erabReleaseReq3gppCauseGroup_15," +
            "erabReleaseReq3gppCause_0,erabReleaseReq3gppCause_1," +
            "erabReleaseReq3gppCause_2,erabReleaseReq3gppCause_3," +
            "erabReleaseReq3gppCause_4,erabReleaseReq3gppCause_5," +
            "erabReleaseReq3gppCause_6,erabReleaseReq3gppCause_7," +
            "erabReleaseReq3gppCause_8,erabReleaseReq3gppCause_9," +
            "erabReleaseReq3gppCause_10,erabReleaseReq3gppCause_11," +
            "erabReleaseReq3gppCause_12,erabReleaseReq3gppCause_13," +
            "erabReleaseReq3gppCause_14,erabReleaseReq3gppCause_15," +
            "erabReleaseSucc_0,erabReleaseSucc_1,erabReleaseSucc_2,erabReleaseSucc_3," +
            "erabReleaseSucc_4,erabReleaseSucc_5,erabReleaseSucc_6,erabReleaseSucc_7," +
            "erabReleaseSucc_8,erabReleaseSucc_9,erabReleaseSucc_10,erabReleaseSucc_11," +
            "erabReleaseSucc_12,erabReleaseSucc_13,erabReleaseSucc_14,erabReleaseSucc_15," +
            "erabReleaseFailure3gppCauseGroup_0,erabReleaseFailure3gppCauseGroup_1," +
            "erabReleaseFailure3gppCauseGroup_2,erabReleaseFailure3gppCauseGroup_3," +
            "erabReleaseFailure3gppCauseGroup_4,erabReleaseFailure3gppCauseGroup_5," +
            "erabReleaseFailure3gppCauseGroup_6,erabReleaseFailure3gppCauseGroup_7," +
            "erabReleaseFailure3gppCauseGroup_8,erabReleaseFailure3gppCauseGroup_9," +
            "erabReleaseFailure3gppCauseGroup_10,erabReleaseFailure3gppCauseGroup_11," +
            "erabReleaseFailure3gppCauseGroup_12,erabReleaseFailure3gppCauseGroup_13," +
            "erabReleaseFailure3gppCauseGroup_14,erabReleaseFailure3gppCauseGroup_15," +
            "erabReleaseFailure3gppCause_0,erabReleaseFailure3gppCause_1," +
            "erabReleaseFailure3gppCause_2,erabReleaseFailure3gppCause_3," +
            "erabReleaseFailure3gppCause_4,erabReleaseFailure3gppCause_5," +
            "erabReleaseFailure3gppCause_6,erabReleaseFailure3gppCause_7," +
            "erabReleaseFailure3gppCause_8,erabReleaseFailure3gppCause_9," +
            "erabReleaseFailure3gppCause_10,erabReleaseFailure3gppCause_11," +
            "erabReleaseFailure3gppCause_12,erabReleaseFailure3gppCause_13," +
            "erabReleaseFailure3gppCause_14,erabReleaseFailure3gppCause_15," +
            "erabSetupReqArp_0,erabSetupReqArp_1,erabSetupReqArp_2,erabSetupReqArp_3," +
            "erabSetupReqArp_4,erabSetupReqArp_5,erabSetupReqArp_6,erabSetupReqArp_7," +
            "erabSetupReqArp_8,erabSetupReqArp_9,erabSetupReqArp_10,erabSetupReqArp_11," +
            "erabSetupReqArp_12,erabSetupReqArp_13,erabSetupReqArp_14,erabSetupReqArp_15," +
            "erabSetupReqPci_0,erabSetupReqPci_1,erabSetupReqPci_2,erabSetupReqPci_3," +
            "erabSetupReqPci_4,erabSetupReqPci_5,erabSetupReqPci_6,erabSetupReqPci_7," +
            "erabSetupReqPci_8,erabSetupReqPci_9,erabSetupReqPci_10,erabSetupReqPci_11," +
            "erabSetupReqPci_12,erabSetupReqPci_13,erabSetupReqPci_14,erabSetupReqPci_15," +
            "erabSetupReqPvi_0,erabSetupReqPvi_1,erabSetupReqPvi_2,erabSetupReqPvi_3," +
            "erabSetupReqPvi_4,erabSetupReqPvi_5,erabSetupReqPvi_6,erabSetupReqPvi_7," +
            "erabSetupReqPvi_8,erabSetupReqPvi_9,erabSetupReqPvi_10,erabSetupReqPvi_11," +
            "erabSetupReqPvi_12,erabSetupReqPvi_13,erabSetupReqPvi_14,erabSetupReqPvi_15," +
            "timestampStartHour," +
            "timestampStartMinute," +
            "timestampStartSecond," +
            "timestampStartMillisec, " +
            "timestampStopHour," +
            "timestampStopMinute," +
            "timestampStopSecond," +
            "timestampStopMillisec," +
            "erabReleaseSuccGbr_0,erabReleaseSuccGbr_1,erabReleaseSuccGbr_2,erabReleaseSuccGbr_3," +
            "erabReleaseSuccGbr_4,erabReleaseSuccGbr_5,erabReleaseSuccGbr_6,erabReleaseSuccGbr_7," +
            "erabReleaseSuccGbr_8,erabReleaseSuccGbr_9,erabReleaseSuccGbr_10,erabReleaseSuccGbr_11," +
            "erabReleaseSuccGbr_12,erabReleaseSuccGbr_13,erabReleaseSuccGbr_14,erabReleaseSuccGbr_15," +
            "erabInactiveGap_0,erabInactiveGap_1,erabInactiveGap_2,erabInactiveGap_3," +
            "erabInactiveGap_4,erabInactiveGap_5,erabInactiveGap_6,erabInactiveGap_7," +
            "erabInactiveGap_8,erabInactiveGap_9,erabInactiveGap_10,erabInactiveGap_11," +
            "erabInactiveGap_12,erabInactiveGap_13,erabInactiveGap_14,erabInactiveGap_15," +
            "tac,svn,maskedsrn,erabReleaseReqBitmap2,plmnIndex,ueCategoryFlex,spidValue," +
            "uePowerClass,brCeLevel,subscriberGroupId,ueEndcStage";

    public static final String EVENT_HEADER_8_RRC_RRC_CONNECTION_RECONFIGURATION = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec,scannerId,rbsModuleId," +
            "globalCellId,enbs1apid,mmes1apid,gummei,racUeRef,traceRecordingSessionReference," +
            "messageDirection,l3messageLength,l3messageContents,crnti";

    public static final String EVENT_HEADER_5_RRC_RRC_CONNECTION_RELEASE = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec,scannerId," +
            "rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei,racUeRef," +
            "traceRecordingSessionReference," +
            "messageDirection,l3messageLength,l3messageContents," +
            "crnti,immciValidity";

    public static final String EVENT_HEADER_4104_PROC_HO_EXEC_S1_OUT = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec,scannerId," +
            "rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei,racUeRef," +
            "traceRecordingSessionReference," +
            "hoSourceOrTargetType,hoTargetSelectionType,neighborCgi," +
            "procHoExecOutResult,drxConfigIndex,hoOutExecErabReqBitmap,hoOutExecErabFailBitmap," +
            "procHoExecOutAttemptCause," +
            "erabHoExecOutQci_0,erabHoExecOutQci_1,erabHoExecOutQci_2,erabHoExecOutQci_3," +
            "erabHoExecOutQci_4,erabHoExecOutQci_5,erabHoExecOutQci_6,erabHoExecOutQci_7," +
            "erabHoExecOutQci_8,erabHoExecOutQci_9,erabHoExecOutQci_10,erabHoExecOutQci_11," +
            "erabHoExecOutQci_12,erabHoExecOutQci_13,erabHoExecOutQci_14,erabHoExecOutQci_15," +
            "timestampStartHour,timestampStartMinute,timestampStartSecond,timestampStartMillisec," +
            "timestampStopHour,timestampStopMinute,timestampStopSecond,timestampStopMillisec," +
            "ta,neighborPci,triggerQuantity,tac,svn,maskedsrn,srvccType,cgiMeasMethodType," +
            "startCgiMeasQci1,hoAfterResync,hoOutExecErabReqBitmap2,hoOutExecErabFailBitmap2," +
            "uePowerClass,plmnIndex,ueCategoryFlex,spidValue,brCeLevel,subscriberGroupId," +
            "ueEndcStage," +
            "erabHoExecOutServiceType_0,erabHoExecOutServiceType_1,erabHoExecOutServiceType_2," +
            "erabHoExecOutServiceType_3,erabHoExecOutServiceType_4,erabHoExecOutServiceType_5," +
            "erabHoExecOutServiceType_6,erabHoExecOutServiceType_7,erabHoExecOutServiceType_8," +
            "erabHoExecOutServiceType_9,erabHoExecOutServiceType_10,erabHoExecOutServiceType_11," +
            "erabHoExecOutServiceType_12,erabHoExecOutServiceType_13,erabHoExecOutServiceType_14," +
            "erabHoExecOutServiceType_15," +
            "neighborNcgi,hoPacketForward" +
            "";

    public static final String EVENT_HEADER_5153_UE_MEAS_INTRAFREQ1 = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec,scannerId,rbsModuleId," +
            "globalCellId,enbs1apid,mmes1apid," +
            "gummei,racUeRef,traceRecordingSessionReference," +
            "measurementId,reportConfigType,rsrpserving,rsrqserving," +
            "physicalCellid1,rsrpresult1,rsrqresult1," +
            "physicalCellid2,rsrpresult2,rsrqresult2," +
            "physicalCellid3,rsrpresult3,rsrqresult3," +
            "physicalCellid4,rsrpresult4,rsrqresult4," +
            "physicalCellid5,rsrpresult5,rsrqresult5," +
            "physicalCellid6,rsrpresult6,rsrqresult6," +
            "physicalCellid7,rsrpresult7,rsrqresult7," +
            "physicalCellid8,rsrpresult8,rsrqresult8";

    public static final String EVENT_HEADER_5267_UE_MEAS_INTERFREQ1 = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei,racUeRef," +
            "traceRecordingSessionReference," +
            "measurementId,reportConfigType,rsrpserving,rsrqserving,freq," +
            "physicalCellid1,rsrpresult1,rsrqresult1," +
            "physicalCellid2,rsrpresult2,rsrqresult2," +
            "physicalCellid3,rsrpresult3,rsrqresult3," +
            "physicalCellid4,rsrpresult4,rsrqresult4," +
            "physicalCellid5,rsrpresult5,rsrqresult5," +
            "physicalCellid6,rsrpresult6,rsrqresult6," +
            "physicalCellid7,rsrpresult7,rsrqresult7," +
            "physicalCellid8,rsrpresult8,rsrqresult8";

    public static final String EVENT_HEADER_5269_UE_MEAS_GERAN1 = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "measurementId,reportConfigType,rsrpserving,rsrqserving,freq," +
            "physicalCellid1,rssiresult1," +
            "physicalCellid2,rssiresult2," +
            "physicalCellid3,rssiresult3," +
            "physicalCellid4,rssiresult4," +
            "physicalCellid5,rssiresult5," +
            "physicalCellid6,rssiresult6," +
            "physicalCellid7,rssiresult7," +
            "physicalCellid8,rssiresult8," +
            "physicalCellid1_2,physicalCellid2_2,physicalCellid3_2,physicalCellid4_2," +
            "physicalCellid5_2,physicalCellid6_2,physicalCellid7_2,physicalCellid8_2," +
            "neighborFreq1,neighborFreq2,neighborFreq3,neighborFreq4," +
            "neighborFreq5,neighborFreq6,neighborFreq7,neighborFreq8";

    public static final String EVENT_HEADER_26_RRC_UE_INFORMATION_RESPONSE = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "messageDirection,l3messageLength,l3messageContents,crnti";

    public static final String EVENT_HEADER_4125_PROC_UE_CTXT_RELEASE = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid," +
            "gummei,racUeRef,traceRecordingSessionReference," +
            "triggeringNode,s1ReleaseCause,param3gppCauseGroup,param3gppCause,internalReleaseCause," +
            "erabDataLost_0,erabDataLost_1,erabDataLost_2,erabDataLost_3," +
            "erabDataLost_4,erabDataLost_5,erabDataLost_6,erabDataLost_7," +
            "erabDataLost_8,erabDataLost_9,erabDataLost_10,erabDataLost_11," +
            "erabDataLost_12,erabDataLost_13,erabDataLost_14,erabDataLost_15," +
            "erabReleaseSucc_0,erabReleaseSucc_1,erabReleaseSucc_2,erabReleaseSucc_3," +
            "erabReleaseSucc_4,erabReleaseSucc_5,erabReleaseSucc_6,erabReleaseSucc_7," +
            "erabReleaseSucc_8,erabReleaseSucc_9,erabReleaseSucc_10,erabReleaseSucc_11," +
            "erabReleaseSucc_12,erabReleaseSucc_13,erabReleaseSucc_14,erabReleaseSucc_15," +
            "erabReleaseReqQci_0,erabReleaseReqQci_1,erabReleaseReqQci_2,erabReleaseReqQci_3," +
            "erabReleaseReqQci_4,erabReleaseReqQci_5,erabReleaseReqQci_6,erabReleaseReqQci_7," +
            "erabReleaseReqQci_8,erabReleaseReqQci_9,erabReleaseReqQci_10,erabReleaseReqQci_11," +
            "erabReleaseReqQci_12,erabReleaseReqQci_13,erabReleaseReqQci_14,erabReleaseReqQci_15," +
            "hoOutPrepErabFail_0,hoOutPrepErabFail_1,hoOutPrepErabFail_2,hoOutPrepErabFail_3," +
            "hoOutPrepErabFail_4,hoOutPrepErabFail_5,hoOutPrepErabFail_6,hoOutPrepErabFail_7," +
            "hoOutPrepErabFail_8,hoOutPrepErabFail_9,hoOutPrepErabFail_10,hoOutPrepErabFail_11," +
            "hoOutPrepErabFail_12,hoOutPrepErabFail_13,hoOutPrepErabFail_14,hoOutPrepErabFail_15," +
            "hoOutPrepErabFailAndDataLost_0,hoOutPrepErabFailAndDataLost_1," +
            "hoOutPrepErabFailAndDataLost_2,hoOutPrepErabFailAndDataLost_3," +
            "hoOutPrepErabFailAndDataLost_4,hoOutPrepErabFailAndDataLost_5," +
            "hoOutPrepErabFailAndDataLost_6,hoOutPrepErabFailAndDataLost_7," +
            "hoOutPrepErabFailAndDataLost_8,hoOutPrepErabFailAndDataLost_9," +
            "hoOutPrepErabFailAndDataLost_10,hoOutPrepErabFailAndDataLost_11," +
            "hoOutPrepErabFailAndDataLost_12,hoOutPrepErabFailAndDataLost_13," +
            "hoOutPrepErabFailAndDataLost_14,hoOutPrepErabFailAndDataLost_15," +
            "hoOutExecErabFailAndDataLost_0,hoOutExecErabFailAndDataLost_1," +
            "hoOutExecErabFailAndDataLost_2,hoOutExecErabFailAndDataLost_3," +
            "hoOutExecErabFailAndDataLost_4,hoOutExecErabFailAndDataLost_5," +
            "hoOutExecErabFailAndDataLost_6,hoOutExecErabFailAndDataLost_7," +
            "hoOutExecErabFailAndDataLost_8,hoOutExecErabFailAndDataLost_9," +
            "hoOutExecErabFailAndDataLost_10,hoOutExecErabFailAndDataLost_11," +
            "hoOutExecErabFailAndDataLost_12,hoOutExecErabFailAndDataLost_13," +
            "hoOutExecErabFailAndDataLost_14,hoOutExecErabFailAndDataLost_15," +
            "erabSetupReqArp_0,erabSetupReqArp_1,erabSetupReqArp_2,erabSetupReqArp_3," +
            "erabSetupReqArp_4,erabSetupReqArp_5,erabSetupReqArp_6,erabSetupReqArp_7," +
            "erabSetupReqArp_8,erabSetupReqArp_9,erabSetupReqArp_10,erabSetupReqArp_11," +
            "erabSetupReqArp_12,erabSetupReqArp_13,erabSetupReqArp_14,erabSetupReqArp_15," +
            "erabSetupReqPci_0,erabSetupReqPci_1,erabSetupReqPci_2,erabSetupReqPci_3," +
            "erabSetupReqPci_4,erabSetupReqPci_5,erabSetupReqPci_6,erabSetupReqPci_7," +
            "erabSetupReqPci_8,erabSetupReqPci_9,erabSetupReqPci_10,erabSetupReqPci_11," +
            "erabSetupReqPci_12,erabSetupReqPci_13,erabSetupReqPci_14,erabSetupReqPci_15," +
            "erabSetupReqPvi_0,erabSetupReqPvi_1,erabSetupReqPvi_2,erabSetupReqPvi_3," +
            "erabSetupReqPvi_4,erabSetupReqPvi_5,erabSetupReqPvi_6,erabSetupReqPvi_7," +
            "erabSetupReqPvi_8,erabSetupReqPvi_9,erabSetupReqPvi_10,erabSetupReqPvi_11," +
            "erabSetupReqPvi_12,erabSetupReqPvi_13,erabSetupReqPvi_14,erabSetupReqPvi_15," +
            "timestampStartHour,timestampStartMinute,timestampStartSecond,timestampStartMillisec," +
            "timestampStopHour,timestampStopMinute,timestampStopSecond,timestampStopMillisec," +
            "ttiBundlingMode,ta," +
            "partialNodeRestartErabDataLost_0,partialNodeRestartErabDataLost_1," +
            "partialNodeRestartErabDataLost_2,partialNodeRestartErabDataLost_3," +
            "partialNodeRestartErabDataLost_4,partialNodeRestartErabDataLost_5," +
            "partialNodeRestartErabDataLost_6,partialNodeRestartErabDataLost_7," +
            "partialNodeRestartErabDataLost_8,partialNodeRestartErabDataLost_9," +
            "partialNodeRestartErabDataLost_10,partialNodeRestartErabDataLost_11," +
            "partialNodeRestartErabDataLost_12,partialNodeRestartErabDataLost_13," +
            "partialNodeRestartErabDataLost_14,partialNodeRestartErabDataLost_15," +
            "erabReleaseSuccGbr_0,erabReleaseSuccGbr_1,erabReleaseSuccGbr_2,erabReleaseSuccGbr_3," +
            "erabReleaseSuccGbr_4,erabReleaseSuccGbr_5,erabReleaseSuccGbr_6,erabReleaseSuccGbr_7," +
            "erabReleaseSuccGbr_8,erabReleaseSuccGbr_9,erabReleaseSuccGbr_10,erabReleaseSuccGbr_11," +
            "erabReleaseSuccGbr_12,erabReleaseSuccGbr_13,erabReleaseSuccGbr_14,erabReleaseSuccGbr_15," +
            "hoOutPrepErabFailGbr_0,hoOutPrepErabFailGbr_1," +
            "hoOutPrepErabFailGbr_2,hoOutPrepErabFailGbr_3," +
            "hoOutPrepErabFailGbr_4,hoOutPrepErabFailGbr_5," +
            "hoOutPrepErabFailGbr_6,hoOutPrepErabFailGbr_7," +
            "hoOutPrepErabFailGbr_8,hoOutPrepErabFailGbr_9," +
            "hoOutPrepErabFailGbr_10,hoOutPrepErabFailGbr_11," +
            "hoOutPrepErabFailGbr_12,hoOutPrepErabFailGbr_13," +
            "hoOutPrepErabFailGbr_14,hoOutPrepErabFailGbr_15," +
            "hoOutPrepErabFailAndDataLostGbr_0,hoOutPrepErabFailAndDataLostGbr_1," +
            "hoOutPrepErabFailAndDataLostGbr_2,hoOutPrepErabFailAndDataLostGbr_3," +
            "hoOutPrepErabFailAndDataLostGbr_4,hoOutPrepErabFailAndDataLostGbr_5," +
            "hoOutPrepErabFailAndDataLostGbr_6,hoOutPrepErabFailAndDataLostGbr_7," +
            "hoOutPrepErabFailAndDataLostGbr_8,hoOutPrepErabFailAndDataLostGbr_9," +
            "hoOutPrepErabFailAndDataLostGbr_10,hoOutPrepErabFailAndDataLostGbr_11," +
            "hoOutPrepErabFailAndDataLostGbr_12,hoOutPrepErabFailAndDataLostGbr_13," +
            "hoOutPrepErabFailAndDataLostGbr_14,hoOutPrepErabFailAndDataLostGbr_15," +
            "erabInactiveGap_0,erabInactiveGap_1,erabInactiveGap_2,erabInactiveGap_3," +
            "erabInactiveGap_4,erabInactiveGap_5,erabInactiveGap_6,erabInactiveGap_7," +
            "erabInactiveGap_8,erabInactiveGap_9,erabInactiveGap_10,erabInactiveGap_11," +
            "erabInactiveGap_12,erabInactiveGap_13,erabInactiveGap_14,erabInactiveGap_15," +
            "tac,svn,maskedsrn,plmnIndex,ueCategoryFlex,spidValue,uePowerClass," +
            "brCeLevel,subscriberGroupId,uePreemptionCause,ueEndcStage,oldCombinedCovState," +
            "currentCombinedCovState" +
            "" +
            "";


    public static final String EVENT_HEADER_4121_PROC_RRC_CONNECTION_RE_ESTABLISHMENT = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisecond," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "timestampStartHour,timestampStartMinute,timestampStartSecond,timestampStartMillisecond," +
            "timestampStopHour,timestampStopMinute,timestampStopSecond,timestampStopMillisecond," +
            "reestabCause,reestabResult,reestabMultiTargetType," +
            "hoSourceOrTargetType,hoType,ttiBundlingMode,admCtrlRejectingMsrPreemptionAttempted,ta," +
            "erabReestReqQci_0,erabReestReqQci_1,erabReestReqQci_2,erabReestReqQci_3," +
            "erabReestReqQci_4,erabReestReqQci_5,erabReestReqQci_6,erabReestReqQci_7," +
            "erabReestReqQci_8,erabReestReqQci_9,erabReestReqQci_10,erabReestReqQci_11," +
            "erabReestReqQci_12,erabReestReqQci_13,erabReestReqQci_14,erabReestReqQci_15," +
            "erabReestResult_0,erabReestResult_1,erabReestResult_2,erabReestResult_3," +
            "erabReestResult_4,erabReestResult_5,erabReestResult_6,erabReestResult_7," +
            "erabReestResult_8,erabReestResult_9,erabReestResult_10,erabReestResult_11," +
            "erabReestResult_12,erabReestResult_13,erabReestResult_14,erabReestResult_15," +
            "tac,svn,maskedsrn," +
            "msrUlPrbUtilCellState,msrUlPrbUtilBbmState," +
            "msrDlPrbUtilCellState,msrDlPrbUtilBbmState," +
            "msrUlSeUtilCellState,msrUlSeUtilBbmState," +
            "msrDlSeUtilCellState,msrDlSeUtilBbmState," +
            "msrCceUtilCellState,msrUlBbCapUtilBbmState,msrDlBbCapUtilBbmState," +
            "asn1Extension,reestabCauseNb,uePowerClass,subscriberGroupId,pdcpTypeInSource,ueEndcStage," +
            "reestabSourceEnbCandidateOtherVendor,reestabSourceEnbCandidateEricsson," +
            "reestabSourceEnbOtherVendor," +
            "msrDlPrbPttReservationCellState,msrDlSePttReservationCellState," +
            "msrCcePttReservationCellState,msrDlPrbPttReservationBbmState," +
            "msrDlSePttReservationBbmState,msrDlBbCapPttReservationBbmState," +
            "paUser," +
            "erabReestReqArp_0,erabReestReqArp_1,erabReestReqArp_2,erabReestReqArp_3," +
            "erabReestReqArp_4,erabReestReqArp_5,erabReestReqArp_6,erabReestReqArp_7," +
            "erabReestReqArp_8,erabReestReqArp_9,erabReestReqArp_10,erabReestReqArp_11," +
            "erabReestReqArp_12,erabReestReqArp_13,erabReestReqArp_14,erabReestReqArp_15";

    public static final String EVENT_HEADER_4097_PROC_RRC_CONN_SETUP = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "initialUeIdentityType,initialUeIdentity,rrcEstabCause,rrcResult," +
            "timestampStartHour,timestampStartMinute,timestampStartSecond,timestampStartMillisec," +
            "timestampStopHour,timestampStopMinute,timestampStopSecond,timestampStopMillisec," +
            "gummeiType,admCtrlRejectingMsrPreemptionAttempted,admCtrlBlockingArp," +
            "msrUlPrbUtilCellState,msrUlPrbUtilBbmState," +
            "msrDlPrbUtilCellState,msrDlPrbUtilBbmState," +
            "msrUlSeUtilCellState,msrUlSeUtilBbmState," +
            "msrDlSeUtilCellState,msrDlSeUtilBbmState," +
            "msrCceUtilCellState,msrUlBbCapUtilBbmState,msrDlBbCapUtilBbmState," +
            "bandwidthReducedAccessCeMode,rrcEstablCauseNb,brCeLevel," +
            "msrDlPrbPttReservationCellState,msrDlSePttReservationCellState," +
            "msrCcePttReservationCellState," +
            "msrDlPrbPttReservationBbmState,msrDlSePttReservationBbmState," +
            "msrDlBbCapPttReservationBbmState,duacPagingPool,reattemptIndicator";

    public static final String EVENT_HEADER_4106_PROC_INITIAL_CTXT_SETUP = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "erabSetupResult_0,erabSetupResult_1,erabSetupResult_2,erabSetupResult_3," +
            "erabSetupResult_4,erabSetupResult_5,erabSetupResult_6,erabSetupResult_7," +
            "erabSetupResult_8,erabSetupResult_9,erabSetupResult_10,erabSetupResult_11," +
            "erabSetupResult_12,erabSetupResult_13,erabSetupResult_14,erabSetupResult_15," +
            "erabSetupReqQci_0,erabSetupReqQci_1,erabSetupReqQci_2,erabSetupReqQci_3," +
            "erabSetupReqQci_4,erabSetupReqQci_5,erabSetupReqQci_6,erabSetupReqQci_7," +
            "erabSetupReqQci_8,erabSetupReqQci_9,erabSetupReqQci_10,erabSetupReqQci_11," +
            "erabSetupReqQci_12,erabSetupReqQci_13,erabSetupReqQci_14,erabSetupReqQci_15," +
            "erabSetupReqArp_0,erabSetupReqArp_1,erabSetupReqArp_2,erabSetupReqArp_3," +
            "erabSetupReqArp_4,erabSetupReqArp_5,erabSetupReqArp_6,erabSetupReqArp_7," +
            "erabSetupReqArp_8,erabSetupReqArp_9,erabSetupReqArp_10,erabSetupReqArp_11," +
            "erabSetupReqArp_12,erabSetupReqArp_13,erabSetupReqArp_14,erabSetupReqArp_15," +
            "erabSetupReqPci_0,erabSetupReqPci_1,erabSetupReqPci_2,erabSetupReqPci_3," +
            "erabSetupReqPci_4,erabSetupReqPci_5,erabSetupReqPci_6,erabSetupReqPci_7," +
            "erabSetupReqPci_8,erabSetupReqPci_9,erabSetupReqPci_10,erabSetupReqPci_11," +
            "erabSetupReqPci_12,erabSetupReqPci_13,erabSetupReqPci_14,erabSetupReqPci_15," +
            "erabSetupReqPvi_0,erabSetupReqPvi_1,erabSetupReqPvi_2,erabSetupReqPvi_3," +
            "erabSetupReqPvi_4,erabSetupReqPvi_5,erabSetupReqPvi_6,erabSetupReqPvi_7," +
            "erabSetupReqPvi_8,erabSetupReqPvi_9,erabSetupReqPvi_10,erabSetupReqPvi_11," +
            "erabSetupReqPvi_12,erabSetupReqPvi_13,erabSetupReqPvi_14,erabSetupReqPvi_15," +
            "erabSetupAttAccType_0,erabSetupAttAccType_1,erabSetupAttAccType_2,erabSetupAttAccType_3," +
            "erabSetupAttAccType_4,erabSetupAttAccType_5,erabSetupAttAccType_6,erabSetupAttAccType_7," +
            "erabSetupAttAccType_8,erabSetupAttAccType_9,erabSetupAttAccType_10,erabSetupAttAccType_11," +
            "erabSetupAttAccType_12,erabSetupAttAccType_13,erabSetupAttAccType_14,erabSetupAttAccType_15," +
            "erabSetupSuccAccType_0,erabSetupSuccAccType_1,erabSetupSuccAccType_2," +
            "erabSetupSuccAccType_3,erabSetupSuccAccType_4,erabSetupSuccAccType_5," +
            "erabSetupSuccAccType_6,erabSetupSuccAccType_7,erabSetupSuccAccType_8," +
            "erabSetupSuccAccType_9,erabSetupSuccAccType_10,erabSetupSuccAccType_11," +
            "erabSetupSuccAccType_12,erabSetupSuccAccType_13,erabSetupSuccAccType_14," +
            "erabSetupSuccAccType_15," +
            "erabSetupFailure3gppCauseGroup_0,erabSetupFailure3gppCauseGroup_1," +
            "erabSetupFailure3gppCauseGroup_2,erabSetupFailure3gppCauseGroup_3," +
            "erabSetupFailure3gppCauseGroup_4,erabSetupFailure3gppCauseGroup_5," +
            "erabSetupFailure3gppCauseGroup_6,erabSetupFailure3gppCauseGroup_7," +
            "erabSetupFailure3gppCauseGroup_8,erabSetupFailure3gppCauseGroup_9," +
            "erabSetupFailure3gppCauseGroup_10,erabSetupFailure3gppCauseGroup_11," +
            "erabSetupFailure3gppCauseGroup_12,erabSetupFailure3gppCauseGroup_13," +
            "erabSetupFailure3gppCauseGroup_14,erabSetupFailure3gppCauseGroup_15," +
            "erabSetupFailure3gppCause_0,erabSetupFailure3gppCause_1,erabSetupFailure3gppCause_2," +
            "erabSetupFailure3gppCause_3,erabSetupFailure3gppCause_4,erabSetupFailure3gppCause_5," +
            "erabSetupFailure3gppCause_6,erabSetupFailure3gppCause_7,erabSetupFailure3gppCause_8," +
            "erabSetupFailure3gppCause_9,erabSetupFailure3gppCause_10,erabSetupFailure3gppCause_11," +
            "erabSetupFailure3gppCause_12,erabSetupFailure3gppCause_13,erabSetupFailure3gppCause_14," +
            "erabSetupFailure3gppCause_15," +
            "accumulatedUlRequestedGbr,accumulatedDlRequestedGbr," +
            "accumulatedUlAdmittedGbr,accumulatedDlAdmittedGbr," +
            "initialCtxtResult,servingPlmnId,param3gppCauseGroup,param3gppCause," +
            "timestampStartHour,timestampStartMinute,timestampStartSecond,timestampStartMillisec," +
            "timestampStopHour,timestampStopMinute,timestampStopSecond,timestampStopMillisec," +
            "ta," +
            "erabAdmCtrlBlockingArp_0,erabAdmCtrlBlockingArp_1,erabAdmCtrlBlockingArp_2," +
            "erabAdmCtrlBlockingArp_3,erabAdmCtrlBlockingArp_4,erabAdmCtrlBlockingArp_5," +
            "erabAdmCtrlBlockingArp_6,erabAdmCtrlBlockingArp_7,erabAdmCtrlBlockingArp_8," +
            "erabAdmCtrlBlockingArp_9,erabAdmCtrlBlockingArp_10,erabAdmCtrlBlockingArp_11," +
            "erabAdmCtrlBlockingArp_12,erabAdmCtrlBlockingArp_13,erabAdmCtrlBlockingArp_14," +
            "erabAdmCtrlBlockingArp_15," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_0," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_1," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_2," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_3," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_4," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_5," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_6," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_7," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_8," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_9," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_10," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_11," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_12," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_13," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_14," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_15," +
            "ueHighestRecArp,ueAdmCtrlBlockingArp," +
            "erabSetupAttemptGbr_0,erabSetupAttemptGbr_1,erabSetupAttemptGbr_2,erabSetupAttemptGbr_3," +
            "erabSetupAttemptGbr_4,erabSetupAttemptGbr_5,erabSetupAttemptGbr_6,erabSetupAttemptGbr_7," +
            "erabSetupAttemptGbr_8,erabSetupAttemptGbr_9,erabSetupAttemptGbr_10,erabSetupAttemptGbr_11," +
            "erabSetupAttemptGbr_12,erabSetupAttemptGbr_13,erabSetupAttemptGbr_14,erabSetupAttemptGbr_15," +
            "erabSetupResultSuccReqGbr_0,erabSetupResultSuccReqGbr_1,erabSetupResultSuccReqGbr_2," +
            "erabSetupResultSuccReqGbr_3,erabSetupResultSuccReqGbr_4,erabSetupResultSuccReqGbr_5," +
            "erabSetupResultSuccReqGbr_6,erabSetupResultSuccReqGbr_7,erabSetupResultSuccReqGbr_8," +
            "erabSetupResultSuccReqGbr_9,erabSetupResultSuccReqGbr_10,erabSetupResultSuccReqGbr_11," +
            "erabSetupResultSuccReqGbr_12,erabSetupResultSuccReqGbr_13,erabSetupResultSuccReqGbr_14," +
            "erabSetupResultSuccReqGbr_15," +
            "tac,svn,maskedsrn,plmnIndex,ueCategoryFlex,spidValue," +
            "bandwidthReducedAccessCeMode,uePowerClass,brCeLevel,subscriberGroupId," +
            "erabSetupResultGbr_0,erabSetupResultGbr_1,erabSetupResultGbr_2,erabSetupResultGbr_3," +
            "erabSetupResultGbr_4,erabSetupResultGbr_5,erabSetupResultGbr_6,erabSetupResultGbr_7," +
            "erabSetupResultGbr_8,erabSetupResultGbr_9,erabSetupResultGbr_10,erabSetupResultGbr_11," +
            "erabSetupResultGbr_12,erabSetupResultGbr_13,erabSetupResultGbr_14,erabSetupResultGbr_15," +
            "erabSetupResFailResult_0,erabSetupResFailResult_1,erabSetupResFailResult_2," +
            "erabSetupResFailResult_3,erabSetupResFailResult_4,erabSetupResFailResult_5," +
            "erabSetupResFailResult_6,erabSetupResFailResult_7,erabSetupResFailResult_8," +
            "erabSetupResFailResult_9,erabSetupResFailResult_10,erabSetupResFailResult_11," +
            "erabSetupResFailResult_12,erabSetupResFailResult_13,erabSetupResFailResult_14," +
            "erabSetupResFailResult_15," +
            "erabSetupResFailResultGbr_0,erabSetupResFailResultGbr_1,erabSetupResFailResultGbr_2," +
            "erabSetupResFailResultGbr_3,erabSetupResFailResultGbr_4,erabSetupResFailResultGbr_5," +
            "erabSetupResFailResultGbr_6,erabSetupResFailResultGbr_7,erabSetupResFailResultGbr_8," +
            "erabSetupResFailResultGbr_9,erabSetupResFailResultGbr_10,erabSetupResFailResultGbr_11," +
            "erabSetupResFailResultGbr_12,erabSetupResFailResultGbr_13,erabSetupResFailResultGbr_14," +
            "erabSetupResFailResultGbr_15," +
            "ueEndcStage";

    public static final String EVENT_HEADER_4110_PROC_HO_PREP_X2_OUT = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "hoSourceOrTargetType,hoTargetSelectionType," +
            "neighborCgi,procHoPrepOutAttemptCause,procHoPrepOutResult," +
            "hoType,hoOutPrepErabReqBitmap,hoOutPrepErabFailBitmap," +
            "param3gppCauseGroup,param3gppCause," +
            "hoPrepQci_0,hoPrepQci_1,hoPrepQci_2,hoPrepQci_3,hoPrepQci_4,hoPrepQci_5," +
            "hoPrepQci_6,hoPrepQci_7,hoPrepQci_8,hoPrepQci_9,hoPrepQci_10,hoPrepQci_11," +
            "hoPrepQci_12,hoPrepQci_13,hoPrepQci_14,hoPrepQci_15," +
            "timestampStartHour,timestampStartMinute,timestampStartSecond,timestampStartMillisec," +
            "timestampStopHour,timestampStopMinute,timestampStopSecond,timestampStopMillisec," +
            "tac,svn,maskedsrn,ulEvaluation,sinrMaxRsrpSource,noiseInterferenceSource," +
            "sinrMaxRsrpTarget,noiseInterferenceTarget,ultrigRejectCause," +
            "hoOutPrepErabReqBitmap2,hoOutPrepErabFailBitmap2," +
            "uePowerClass,subscriberGroupId,ueCategoryFlex,brCeLevel,plmnIndex,spidValue,ueEndcStage";

    public static final String EVENT_HEADER_4112_PROC_HO_EXEC_X2_OUT = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "hoSourceOrTargetType,hoTargetSelectionType,neighborCgi," +
            "hoPacketForward,procHoExecOutResult,hoType,drxConfigIndex," +
            "hoOutExecErabReqBitmap,hoOutExecErabFailBitmap," +
            "procHoExecOutAttemptCause," +
            "erabHoExecOutQci_0,erabHoExecOutQci_1,erabHoExecOutQci_2,erabHoExecOutQci_3," +
            "erabHoExecOutQci_4,erabHoExecOutQci_5,erabHoExecOutQci_6,erabHoExecOutQci_7," +
            "erabHoExecOutQci_8,erabHoExecOutQci_9,erabHoExecOutQci_10,erabHoExecOutQci_11," +
            "erabHoExecOutQci_12,erabHoExecOutQci_13,erabHoExecOutQci_14,erabHoExecOutQci_15," +
            "timestampStartHour,timestampStartMinute,timestampStartSecond,timestampStartMillisec," +
            "timestampStopHour,timestampStopMinute,timestampStopSecond,timestampStopMillisec," +
            "ta,triggerQuantity,tac,svn,maskedsrn,hoAfterResync,hoStickyEarfcn," +
            "hoOutExecErabReqBitmap2,hoOutExecErabFailBitmap2," +
            "uePowerClass,subscriberGroupId,ueCategoryFlex,brCeLevel,plmnIndex," +
            "spidValue,ueEndcStage," +
            "erabHoExecOutServiceType_0,erabHoExecOutServiceType_1,erabHoExecOutServiceType_2," +
            "erabHoExecOutServiceType_3,erabHoExecOutServiceType_4,erabHoExecOutServiceType_5," +
            "erabHoExecOutServiceType_6,erabHoExecOutServiceType_7,erabHoExecOutServiceType_8," +
            "erabHoExecOutServiceType_9,erabHoExecOutServiceType_10,erabHoExecOutServiceType_11," +
            "erabHoExecOutServiceType_12,erabHoExecOutServiceType_13,erabHoExecOutServiceType_14," +
            "erabHoExecOutServiceType_15";

    public static final String EVENT_HEADER_4099_ERAB_SETUP = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisec," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "erabSetupResult_0,erabSetupResult_1,erabSetupResult_2,erabSetupResult_3," +
            "erabSetupResult_4,erabSetupResult_5,erabSetupResult_6,erabSetupResult_7," +
            "erabSetupResult_8,erabSetupResult_9,erabSetupResult_10,erabSetupResult_11," +
            "erabSetupResult_12,erabSetupResult_13,erabSetupResult_14,erabSetupResult_15," +
            "erabSetupReqQci_0,erabSetupReqQci_1,erabSetupReqQci_2,erabSetupReqQci_3," +
            "erabSetupReqQci_4,erabSetupReqQci_5,erabSetupReqQci_6,erabSetupReqQci_7," +
            "erabSetupReqQci_8,erabSetupReqQci_9,erabSetupReqQci_10,erabSetupReqQci_11," +
            "erabSetupReqQci_12,erabSetupReqQci_13,erabSetupReqQci_14,erabSetupReqQci_15," +
            "erabSetupReqArp_0,erabSetupReqArp_1,erabSetupReqArp_2,erabSetupReqArp_3," +
            "erabSetupReqArp_4,erabSetupReqArp_5,erabSetupReqArp_6,erabSetupReqArp_7," +
            "erabSetupReqArp_8,erabSetupReqArp_9,erabSetupReqArp_10,erabSetupReqArp_11," +
            "erabSetupReqArp_12,erabSetupReqArp_13,erabSetupReqArp_14,erabSetupReqArp_15," +
            "erabSetupReqPci_0,erabSetupReqPci_1,erabSetupReqPci_2,erabSetupReqPci_3," +
            "erabSetupReqPci_4,erabSetupReqPci_5,erabSetupReqPci_6,erabSetupReqPci_7," +
            "erabSetupReqPci_8,erabSetupReqPci_9,erabSetupReqPci_10,erabSetupReqPci_11," +
            "erabSetupReqPci_12,erabSetupReqPci_13,erabSetupReqPci_14,erabSetupReqPci_15," +
            "erabSetupReqPvi_0,erabSetupReqPvi_1,erabSetupReqPvi_2,erabSetupReqPvi_3," +
            "erabSetupReqPvi_4,erabSetupReqPvi_5,erabSetupReqPvi_6,erabSetupReqPvi_7," +
            "erabSetupReqPvi_8,erabSetupReqPvi_9,erabSetupReqPvi_10,erabSetupReqPvi_11," +
            "erabSetupReqPvi_12,erabSetupReqPvi_13,erabSetupReqPvi_14,erabSetupReqPvi_15," +
            "erabSetupAttAccType_0,erabSetupAttAccType_1,erabSetupAttAccType_2,erabSetupAttAccType_3," +
            "erabSetupAttAccType_4,erabSetupAttAccType_5,erabSetupAttAccType_6,erabSetupAttAccType_7," +
            "erabSetupAttAccType_8,erabSetupAttAccType_9,erabSetupAttAccType_10,erabSetupAttAccType_11," +
            "erabSetupAttAccType_12,erabSetupAttAccType_13,erabSetupAttAccType_14,erabSetupAttAccType_15," +
            "erabSetupSuccAccType_0,erabSetupSuccAccType_1,erabSetupSuccAccType_2," +
            "erabSetupSuccAccType_3,erabSetupSuccAccType_4,erabSetupSuccAccType_5," +
            "erabSetupSuccAccType_6,erabSetupSuccAccType_7,erabSetupSuccAccType_8," +
            "erabSetupSuccAccType_9,erabSetupSuccAccType_10,erabSetupSuccAccType_11," +
            "erabSetupSuccAccType_12,erabSetupSuccAccType_13,erabSetupSuccAccType_14," +
            "erabSetupSuccAccType_15," +
            "erabSetupFailure3gppCauseGroup_0,erabSetupFailure3gppCauseGroup_1," +
            "erabSetupFailure3gppCauseGroup_2,erabSetupFailure3gppCauseGroup_3," +
            "erabSetupFailure3gppCauseGroup_4,erabSetupFailure3gppCauseGroup_5," +
            "erabSetupFailure3gppCauseGroup_6,erabSetupFailure3gppCauseGroup_7," +
            "erabSetupFailure3gppCauseGroup_8,erabSetupFailure3gppCauseGroup_9," +
            "erabSetupFailure3gppCauseGroup_10,erabSetupFailure3gppCauseGroup_11," +
            "erabSetupFailure3gppCauseGroup_12,erabSetupFailure3gppCauseGroup_13," +
            "erabSetupFailure3gppCauseGroup_14,erabSetupFailure3gppCauseGroup_15," +
            "erabSetupFailure3gppCause_0,erabSetupFailure3gppCause_1,erabSetupFailure3gppCause_2," +
            "erabSetupFailure3gppCause_3,erabSetupFailure3gppCause_4,erabSetupFailure3gppCause_5," +
            "erabSetupFailure3gppCause_6,erabSetupFailure3gppCause_7,erabSetupFailure3gppCause_8," +
            "erabSetupFailure3gppCause_9,erabSetupFailure3gppCause_10,erabSetupFailure3gppCause_11," +
            "erabSetupFailure3gppCause_12,erabSetupFailure3gppCause_13,erabSetupFailure3gppCause_14," +
            "erabSetupFailure3gppCause_15," +
            "accumulatedUlRequestedGbr,accumulatedDlRequestedGbr," +
            "accumulatedUlAdmittedGbr,accumulatedDlAdmittedGbr," +
            "timestampStartHour,timestampStartMinute,timestampStartSecond,timestampStartMillisec," +
            "timestampStopHour,timestampStopMinute,timestampStopSecond,timestampStopMillisec," +
            "erabAdmCtrlBlockingArp_0,erabAdmCtrlBlockingArp_1,erabAdmCtrlBlockingArp_2," +
            "erabAdmCtrlBlockingArp_3,erabAdmCtrlBlockingArp_4,erabAdmCtrlBlockingArp_5," +
            "erabAdmCtrlBlockingArp_6,erabAdmCtrlBlockingArp_7,erabAdmCtrlBlockingArp_8," +
            "erabAdmCtrlBlockingArp_9,erabAdmCtrlBlockingArp_10,erabAdmCtrlBlockingArp_11," +
            "erabAdmCtrlBlockingArp_12,erabAdmCtrlBlockingArp_13,erabAdmCtrlBlockingArp_14," +
            "erabAdmCtrlBlockingArp_15," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_0," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_1," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_2," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_3," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_4," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_5," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_6," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_7," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_8," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_9," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_10," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_11," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_12," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_13," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_14," +
            "erabAdmCtrlRejectingMsrPreemptionAttempted_15," +
            "erabSetupResultSuccReqGbr_0,erabSetupResultSuccReqGbr_1,erabSetupResultSuccReqGbr_2," +
            "erabSetupResultSuccReqGbr_3,erabSetupResultSuccReqGbr_4,erabSetupResultSuccReqGbr_5," +
            "erabSetupResultSuccReqGbr_6,erabSetupResultSuccReqGbr_7,erabSetupResultSuccReqGbr_8," +
            "erabSetupResultSuccReqGbr_9,erabSetupResultSuccReqGbr_10,erabSetupResultSuccReqGbr_11," +
            "erabSetupResultSuccReqGbr_12,erabSetupResultSuccReqGbr_13,erabSetupResultSuccReqGbr_14," +
            "erabSetupResultSuccReqGbr_15," +
            "tac,svn,maskedsrn,plmnIndex,ueCategoryFlex,spidValue," +
            "uePowerClass,brCeLevel,subscriberGroupId," +
            "erabSetupResultGbr_0,erabSetupResultGbr_1,erabSetupResultGbr_2,erabSetupResultGbr_3," +
            "erabSetupResultGbr_4,erabSetupResultGbr_5,erabSetupResultGbr_6,erabSetupResultGbr_7," +
            "erabSetupResultGbr_8,erabSetupResultGbr_9,erabSetupResultGbr_10,erabSetupResultGbr_11," +
            "erabSetupResultGbr_12,erabSetupResultGbr_13,erabSetupResultGbr_14,erabSetupResultGbr_15," +
            "erabSetupResFailResult_0,erabSetupResFailResult_1,erabSetupResFailResult_2," +
            "erabSetupResFailResult_3,erabSetupResFailResult_4,erabSetupResFailResult_5," +
            "erabSetupResFailResult_6,erabSetupResFailResult_7,erabSetupResFailResult_8," +
            "erabSetupResFailResult_9,erabSetupResFailResult_10,erabSetupResFailResult_11," +
            "erabSetupResFailResult_12,erabSetupResFailResult_13,erabSetupResFailResult_14," +
            "erabSetupResFailResult_15," +
            "erabSetupResFailResultGbr_0,erabSetupResFailResultGbr_1,erabSetupResFailResultGbr_2," +
            "erabSetupResFailResultGbr_3,erabSetupResFailResultGbr_4,erabSetupResFailResultGbr_5," +
            "erabSetupResFailResultGbr_6,erabSetupResFailResultGbr_7,erabSetupResFailResultGbr_8," +
            "erabSetupResFailResultGbr_9,erabSetupResFailResultGbr_10,erabSetupResFailResultGbr_11," +
            "erabSetupResFailResultGbr_12,erabSetupResFailResultGbr_13,erabSetupResFailResultGbr_14," +
            "erabSetupResFailResultGbr_15," +
            "ueEndcStage";

    public static final String EVENT_HEADER_3129_MDT6_UL = "Datetime,Within_Start_&_End_Time,timestamp_hour,timestamp_minute,timestamp_second,timestamp_millisecond," +
            "scanner_id,rbs_module_id,global_cell_id,enbs1apid,mmes1apid,gummei," +
            "rac_ue_ref,trace_recording_session_reference," +
            "erab_exc_delay_ul_0,erab_exc_delay_ul_1,erab_exc_delay_ul_2," +
            "erab_exc_delay_ul_3,erab_exc_delay_ul_4,erab_exc_delay_ul_5," +
            "erab_qci_ul_0,erab_qci_ul_1,erab_qci_ul_2," +
            "erab_qci_ul_3,erab_qci_ul_4,erab_qci_ul_5," +
            "mdt_m6_location_coordinates," +
            "mdt_m6_ellipsoid_point_latitude_sign,mdt_m6_ellipsoid_point_degrees_latitude," +
            "mdt_m6_ellipsoid_point_degrees_longitude," +
            "mdt_m6_ellipsoid_point_with_alti_latitude_sign," +
            "mdt_m6_ellipsoid_point_with_alti_degrees_latitude," +
            "mdt_m6_ellipsoid_point_with_alti_degrees_longitude," +
            "mdt_m6_ellipsoid_point_with_alti_altitude_direction," +
            "mdt_m6_ellipsoid_point_with_alti_altitude," +
            "mdt_m6_ellipsoid_point_with_uncer_circle_latitude_sign," +
            "mdt_m6_ellipsoid_point_with_uncer_circle_degrees_latitude," +
            "mdt_m6_ellipsoid_point_with_uncer_circle_degrees_longitude," +
            "mdt_m6_ellipsoid_point_with_uncer_circle_uncertainty," +
            "mdt_m6_ellipsoid_point_with_uncer_ellipse_latitude_sign," +
            "mdt_m6_ellipsoid_point_with_uncer_ellipse_degrees_latitude," +
            "mdt_m6_ellipsoid_point_with_uncer_ellipse_degrees_longitude," +
            "mdt_m6_ellipsoid_point_with_uncer_ellipse_uncertainty_semi_major," +
            "mdt_m6_ellipsoid_point_with_uncer_ellipse_uncertainty_semi_minor," +
            "mdt_m6_ellipsoid_point_with_uncer_ellipse_orientaion_major_axis," +
            "mdt_m6_ellipsoid_point_with_uncer_ellipse_confidence," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_latitude_sign," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_degrees_latitude," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_degrees_longitude," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_altitude_direction," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_altitude," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_uncertainty_semi_major," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_uncertainty_semi_minor," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_orientaion_major_axis," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_uncertainty_altitude," +
            "mdt_m6_ellipsoid_point_with_alti_and_uncer_ellipsoid_confidence," +
            "mdt_m6_ellipsoid_arc_latitude_sign," +
            "mdt_m6_ellipsoid_arc_degrees_latitude," +
            "mdt_m6_ellipsoid_arc_degrees_longitude," +
            "mdt_m6_ellipsoid_arc_inner_radius," +
            "mdt_m6_ellipsoid_arc_uncertainty_radius," +
            "mdt_m6_ellipsoid_arc_offset_angle," +
            "mdt_m6_ellipsoid_arc_included_angle," +
            "mdt_m6_ellipsoid_arc_confidence," +
            "mdt_m6_polygon1_latitude_sign,mdt_m6_polygon1_degrees_latitude," +
            "mdt_m6_polygon1_degrees_longitude," +
            "mdt_m6_polygon2_latitude_sign,mdt_m6_polygon2_degrees_latitude," +
            "mdt_m6_polygon2_degrees_longitude," +
            "mdt_m6_polygon3_latitude_sign,mdt_m6_polygon3_degrees_latitude," +
            "mdt_m6_polygon3_degrees_longitude," +
            "mdt_m6_polygon4_latitude_sign,mdt_m6_polygon4_degrees_latitude," +
            "mdt_m6_polygon4_degrees_longitude," +
            "mdt_m6_polygon5_latitude_sign,mdt_m6_polygon5_degrees_latitude," +
            "mdt_m6_polygon5_degrees_longitude," +
            "mdt_m6_polygon6_latitude_sign,mdt_m6_polygon6_degrees_latitude," +
            "mdt_m6_polygon6_degrees_longitude," +
            "mdt_m6_polygon7_latitude_sign,mdt_m6_polygon7_degrees_latitude," +
            "mdt_m6_polygon7_degrees_longitude," +
            "mdt_m6_horizontal_velocity_bearing,mdt_m6_horizontal_velocity_horizontal_speed," +
            "mdt_m6_gnss_tod_msec";

    public static final String EVENT_HEADER_3131_MDT7 = "Datetime,Within_Start_&_End_Time,timestamp_hour,timestamp_minute,timestamp_second,timestamp_millisecond," +
            "scanner_id,rbs_module_id,global_cell_id,enbs1apid,mmes1apid,gummei," +
            "rac_ue_ref,trace_recording_session_reference," +
            "mdt_m7_erab_packet_lost_ul_0,mdt_m7_erab_packet_lost_ul_1," +
            "mdt_m7_erab_packet_lost_ul_2,mdt_m7_erab_packet_lost_ul_3," +
            "mdt_m7_erab_packet_lost_ul_4,mdt_m7_erab_packet_lost_ul_5," +
            "mdt_m7_erab_packet_lost_ul_6,mdt_m7_erab_packet_lost_ul_7," +
            "mdt_m7_erab_packet_lost_ul_8,mdt_m7_erab_packet_lost_ul_9," +
            "mdt_m7_erab_packet_lost_ul_10,mdt_m7_erab_packet_lost_ul_11," +
            "mdt_m7_erab_packet_lost_ul_12,mdt_m7_erab_packet_lost_ul_13," +
            "mdt_m7_erab_packet_lost_ul_14,mdt_m7_erab_packet_lost_ul_15," +
            "mdt_m7_erab_packet_rec_ul_0,mdt_m7_erab_packet_rec_ul_1,mdt_m7_erab_packet_rec_ul_2," +
            "mdt_m7_erab_packet_rec_ul_3,mdt_m7_erab_packet_rec_ul_4,mdt_m7_erab_packet_rec_ul_5," +
            "mdt_m7_erab_packet_rec_ul_6,mdt_m7_erab_packet_rec_ul_7,mdt_m7_erab_packet_rec_ul_8," +
            "mdt_m7_erab_packet_rec_ul_9,mdt_m7_erab_packet_rec_ul_10,mdt_m7_erab_packet_rec_ul_11," +
            "mdt_m7_erab_packet_rec_ul_12,mdt_m7_erab_packet_rec_ul_13,mdt_m7_erab_packet_rec_ul_14," +
            "mdt_m7_erab_packet_rec_ul_15," +
            "mdt_m7_erab_packet_lost_pelr_uu_dl_0,mdt_m7_erab_packet_lost_pelr_uu_dl_1," +
            "mdt_m7_erab_packet_lost_pelr_uu_dl_2,mdt_m7_erab_packet_lost_pelr_uu_dl_3," +
            "mdt_m7_erab_packet_lost_pelr_uu_dl_4,mdt_m7_erab_packet_lost_pelr_uu_dl_5," +
            "mdt_m7_erab_packet_lost_pelr_uu_dl_6,mdt_m7_erab_packet_lost_pelr_uu_dl_7," +
            "mdt_m7_erab_packet_lost_pelr_uu_dl_8,mdt_m7_erab_packet_lost_pelr_uu_dl_9," +
            "mdt_m7_erab_packet_lost_pelr_uu_dl_10,mdt_m7_erab_packet_lost_pelr_uu_dl_11," +
            "mdt_m7_erab_packet_lost_pelr_uu_dl_12,mdt_m7_erab_packet_lost_pelr_uu_dl_13," +
            "mdt_m7_erab_packet_lost_pelr_uu_dl_14,mdt_m7_erab_packet_lost_pelr_uu_dl_15," +
            "mdt_m7_erab_packet_tr_dl_0,mdt_m7_erab_packet_tr_dl_1,mdt_m7_erab_packet_tr_dl_2," +
            "mdt_m7_erab_packet_tr_dl_3,mdt_m7_erab_packet_tr_dl_4,mdt_m7_erab_packet_tr_dl_5," +
            "mdt_m7_erab_packet_tr_dl_6,mdt_m7_erab_packet_tr_dl_7,mdt_m7_erab_packet_tr_dl_8," +
            "mdt_m7_erab_packet_tr_dl_9,mdt_m7_erab_packet_tr_dl_10,mdt_m7_erab_packet_tr_dl_11," +
            "mdt_m7_erab_packet_tr_dl_12,mdt_m7_erab_packet_tr_dl_13,mdt_m7_erab_packet_tr_dl_14," +
            "mdt_m7_erab_packet_tr_dl_15," +
            "mdt_m7_erab_qci_0,mdt_m7_erab_qci_1,mdt_m7_erab_qci_2,mdt_m7_erab_qci_3," +
            "mdt_m7_erab_qci_4,mdt_m7_erab_qci_5,mdt_m7_erab_qci_6,mdt_m7_erab_qci_7," +
            "mdt_m7_erab_qci_8,mdt_m7_erab_qci_9,mdt_m7_erab_qci_10,mdt_m7_erab_qci_11," +
            "mdt_m7_erab_qci_12,mdt_m7_erab_qci_13,mdt_m7_erab_qci_14,mdt_m7_erab_qci_15";

    public static final String EVENT_HEADER_3130_MDT6_DL = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisecond," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionReference," +
            "mdtM6ErabLatTimeDl_0,mdtM6ErabLatTimeDl_1,mdtM6ErabLatTimeDl_2,mdtM6ErabLatTimeDl_3," +
            "mdtM6ErabLatTimeDl_4,mdtM6ErabLatTimeDl_5,mdtM6ErabLatTimeDl_6,mdtM6ErabLatTimeDl_7," +
            "mdtM6ErabLatTimeDl_8,mdtM6ErabLatTimeDl_9,mdtM6ErabLatTimeDl_10,mdtM6ErabLatTimeDl_11," +
            "mdtM6ErabLatTimeDl_12,mdtM6ErabLatTimeDl_13,mdtM6ErabLatTimeDl_14,mdtM6ErabLatTimeDl_15," +
            "mdtM6ErabLatSamplDl_0,mdtM6ErabLatSamplDl_1,mdtM6ErabLatSamplDl_2,mdtM6ErabLatSamplDl_3," +
            "mdtM6ErabLatSamplDl_4,mdtM6ErabLatSamplDl_5,mdtM6ErabLatSamplDl_6,mdtM6ErabLatSamplDl_7," +
            "mdtM6ErabLatSamplDl_8,mdtM6ErabLatSamplDl_9,mdtM6ErabLatSamplDl_10,mdtM6ErabLatSamplDl_11," +
            "mdtM6ErabLatSamplDl_12,mdtM6ErabLatSamplDl_13,mdtM6ErabLatSamplDl_14,mdtM6ErabLatSamplDl_15," +
            "mdtM6ErabQciDl_0,mdtM6ErabQciDl_1,mdtM6ErabQciDl_2,mdtM6ErabQciDl_3,mdtM6ErabQciDl_4," +
            "mdtM6ErabQciDl_5,mdtM6ErabQciDl_6,mdtM6ErabQciDl_7,mdtM6ErabQciDl_8,mdtM6ErabQciDl_9," +
            "mdtM6ErabQciDl_10,mdtM6ErabQciDl_11,mdtM6ErabQciDl_12,mdtM6ErabQciDl_13," +
            "mdtM6ErabQciDl_14,mdtM6ErabQciDl_15," +
            "mdtM6ErabDelayTimeDl_0,mdtM6ErabDelayTimeDl_1,mdtM6ErabDelayTimeDl_2," +
            "mdtM6ErabDelayTimeDl_3,mdtM6ErabDelayTimeDl_4,mdtM6ErabDelayTimeDl_5," +
            "mdtM6ErabDelayTimeDl_6,mdtM6ErabDelayTimeDl_7,mdtM6ErabDelayTimeDl_8," +
            "mdtM6ErabDelayTimeDl_9,mdtM6ErabDelayTimeDl_10,mdtM6ErabDelayTimeDl_11," +
            "mdtM6ErabDelayTimeDl_12,mdtM6ErabDelayTimeDl_13,mdtM6ErabDelayTimeDl_14," +
            "mdtM6ErabDelayTimeDl_15," +
            "mdtM6ErabDelaySamplDl_0,mdtM6ErabDelaySamplDl_1,mdtM6ErabDelaySamplDl_2," +
            "mdtM6ErabDelaySamplDl_3,mdtM6ErabDelaySamplDl_4,mdtM6ErabDelaySamplDl_5," +
            "mdtM6ErabDelaySamplDl_6,mdtM6ErabDelaySamplDl_7,mdtM6ErabDelaySamplDl_8," +
            "mdtM6ErabDelaySamplDl_9,mdtM6ErabDelaySamplDl_10,mdtM6ErabDelaySamplDl_11," +
            "mdtM6ErabDelaySamplDl_12,mdtM6ErabDelaySamplDl_13,mdtM6ErabDelaySamplDl_14," +
            "mdtM6ErabDelaySamplDl_15";

    public static final String EVENT_HEADER_3113_MDT5 = "Datetime,Within_Start_&_End_Time,timestamp_hour,timestamp_minute,timestamp_second,timestamp_millisecond," +
            "scanner_id,rbs_module_id,global_cell_id,enbs1apid,mmes1apid,gummei," +
            "rac_ue_ref,trace_recording_session_reference," +
            "mdt_m2_ue_power_headroom_0,mdt_m2_ue_power_headroom_1,mdt_m2_ue_power_headroom_2," +
            "mdt_m2_ue_power_headroom_3,mdt_m2_ue_power_headroom_4,mdt_m2_ue_power_headroom_5," +
            "mdt_m2_ue_power_headroom_6,mdt_m2_ue_power_headroom_7,mdt_m2_ue_power_headroom_8," +
            "mdt_m2_ue_power_headroom_9,mdt_m2_ue_power_headroom_10,mdt_m2_ue_power_headroom_11" +
            ",mdt_m2_ue_power_headroom_12,mdt_m2_ue_power_headroom_13,mdt_m2_ue_power_headroom_14," +
            "mdt_m2_ue_power_headroom_15";

    public static final String EVENT_HEADER_3075_UE_RADIO_MEAS = "Datetime,Within_Start_&_End_Time,timestamp_hour,timestamp_minute,timestamp_second,timestamp_millisec," +
            "scanner_id,rbs_module_id,global_cell_id,enbs1apid,mmes1apid,gummei," +
            "rac_ue_ref,trace_recording_session_reference," +
            "rank_tx_0,rank_tx_1,rank_tx_2,rank_tx_3,rank_tx_4,rank_tx_5,rank_tx_6,rank_tx_7," +
            "cqi_reported_0,cqi_reported_1,cqi_reported_2,cqi_reported_3,cqi_reported_4," +
            "cqi_reported_5,cqi_reported_6,cqi_reported_7,cqi_reported_8,cqi_reported_9," +
            "cqi_reported_10,cqi_reported_11,cqi_reported_12,cqi_reported_13,cqi_reported_14," +
            "cqi_reported_15," +
            "rank_reported_0,rank_reported_1," +
            "tbspwrrestricted,tbspwrunrestricted," +
            "cqi2_reported_0,cqi2_reported_1,cqi2_reported_2,cqi2_reported_3,cqi2_reported_4," +
            "cqi2_reported_5,cqi2_reported_6,cqi2_reported_7,cqi2_reported_8,cqi2_reported_9," +
            "cqi2_reported_10,cqi2_reported_11,cqi2_reported_12,cqi2_reported_13,cqi2_reported_14," +
            "cqi2_reported_15," +
            "out_loop_adj_dl_0,out_loop_adj_dl_1,out_loop_adj_dl_2,out_loop_adj_dl_3," +
            "out_loop_adj_dl_4,out_loop_adj_dl_5,out_loop_adj_dl_6,out_loop_adj_dl_7," +
            "sinr_meas_pusch_0,sinr_meas_pusch_1,sinr_meas_pusch_2,sinr_meas_pusch_3," +
            "sinr_meas_pusch_4,sinr_meas_pusch_5,sinr_meas_pusch_6,sinr_meas_pusch_7," +
            "sinr_meas_pucch_0,sinr_meas_pucch_1,sinr_meas_pucch_2,sinr_meas_pucch_3," +
            "sinr_meas_pucch_4,sinr_meas_pucch_5,sinr_meas_pucch_6,sinr_meas_pucch_7," +
            "delta_sinr_meas_pusch_0,delta_sinr_meas_pusch_1,delta_sinr_meas_pusch_2," +
            "delta_sinr_meas_pusch_3,delta_sinr_meas_pusch_4,delta_sinr_meas_pusch_5," +
            "delta_sinr_meas_pusch_6,delta_sinr_meas_pusch_7," +
            "aoa,power_headroom," +
            "rank_tx_8,rank_tx_9,rank_tx_10,rank_tx_11," +
            "power_headroom_prb_used," +
            "rank_reported_2,rank_reported_3," +
            "last_ri_reported,last_cqi1_reported,last_cqi2_reported," +
            "last_pusch_num_prb_reported,last_pusch_sinr_reported,last_pusch_power_per_prb_reported," +
            "sinr_meas_pusch8," +
            "rank_tx12,rank_tx13," +
            "hom_cqi_reported_0,hom_cqi_reported_1,hom_cqi_reported_2,hom_cqi_reported_3," +
            "hom_cqi_reported_4,hom_cqi_reported_5,hom_cqi_reported_6,hom_cqi_reported_7," +
            "hom_cqi_reported_8,hom_cqi_reported_9,hom_cqi_reported_10,hom_cqi_reported_11," +
            "hom_cqi_reported_12,hom_cqi_reported_13,hom_cqi_reported_14,hom_cqi_reported_15," +
            "hom_cqi2_reported_0,hom_cqi2_reported_1,hom_cqi2_reported_2,hom_cqi2_reported_3," +
            "hom_cqi2_reported_4,hom_cqi2_reported_5,hom_cqi2_reported_6,hom_cqi2_reported_7," +
            "hom_cqi2_reported_8,hom_cqi2_reported_9,hom_cqi2_reported_10,hom_cqi2_reported_11," +
            "hom_cqi2_reported_12,hom_cqi2_reported_13,hom_cqi2_reported_14,hom_cqi2_reported_15," +
            "hom_rank_reported_0,hom_rank_reported_1,hom_rank_reported_2,hom_rank_reported_3," +
            "cqi3_reported_0,cqi3_reported_1,cqi3_reported_2,cqi3_reported_3,cqi3_reported_4," +
            "cqi3_reported_5,cqi3_reported_6,cqi3_reported_7,cqi3_reported_8,cqi3_reported_9," +
            "cqi3_reported_10,cqi3_reported_11,cqi3_reported_12,cqi3_reported_13,cqi3_reported_14," +
            "cqi3_reported_15," +
            "cqi4_reported_0,cqi4_reported_1,cqi4_reported_2,cqi4_reported_3,cqi4_reported_4," +
            "cqi4_reported_5,cqi4_reported_6,cqi4_reported_7,cqi4_reported_8,cqi4_reported_9," +
            "cqi4_reported_10,cqi4_reported_11,cqi4_reported_12,cqi4_reported_13,cqi4_reported_14," +
            "cqi4_reported_15," +
            "hom_cqi3_reported_0,hom_cqi3_reported_1,hom_cqi3_reported_2,hom_cqi3_reported_3," +
            "hom_cqi3_reported_4,hom_cqi3_reported_5,hom_cqi3_reported_6,hom_cqi3_reported_7," +
            "hom_cqi3_reported_8,hom_cqi3_reported_9,hom_cqi3_reported_10,hom_cqi3_reported_11," +
            "hom_cqi3_reported_12,hom_cqi3_reported_13,hom_cqi3_reported_14,hom_cqi3_reported_15," +
            "hom_cqi4_reported_0,hom_cqi4_reported_1,hom_cqi4_reported_2,hom_cqi4_reported_3," +
            "hom_cqi4_reported_4,hom_cqi4_reported_5,hom_cqi4_reported_6,hom_cqi4_reported_7," +
            "hom_cqi4_reported_8,hom_cqi4_reported_9,hom_cqi4_reported_10,hom_cqi4_reported_11," +
            "hom_cqi4_reported_12,hom_cqi4_reported_13,hom_cqi4_reported_14,hom_cqi4_reported_15," +
            "plmn_index,ue_category_flex,spid_value,br_ce_level,ue_power_class,subscriber_group_id," +
            "endc_stage," +
            "cqi_reported_br_0,cqi_reported_br_1,cqi_reported_br_2,cqi_reported_br_3," +
            "cqi_reported_br_4,cqi_reported_br_5,cqi_reported_br_6,cqi_reported_br_7," +
            "cqi_reported_br_8,cqi_reported_br_9,cqi_reported_br_10,cqi_reported_br_11," +
            "cqi_reported_br_12,cqi_reported_br_13,cqi_reported_br_14,cqi_reported_br_15," +
            "mpdcch_out_loop_adj_dl_br_0,mpdcch_out_loop_adj_dl_br_1,mpdcch_out_loop_adj_dl_br_2," +
            "mpdcch_out_loop_adj_dl_br_3,mpdcch_out_loop_adj_dl_br_4,mpdcch_out_loop_adj_dl_br_5," +
            "mpdcch_out_loop_adj_dl_br_6,mpdcch_out_loop_adj_dl_br_7,mpdcch_out_loop_adj_dl_br_8," +
            "mpdcch_out_loop_adj_dl_br_9,mpdcch_out_loop_adj_dl_br_10,mpdcch_out_loop_adj_dl_br_11," +
            "pdsch_out_loop_adj_dl_br_0,pdsch_out_loop_adj_dl_br_1,pdsch_out_loop_adj_dl_br_2," +
            "pdsch_out_loop_adj_dl_br_3,pdsch_out_loop_adj_dl_br_4,pdsch_out_loop_adj_dl_br_5," +
            "pdsch_out_loop_adj_dl_br_6,pdsch_out_loop_adj_dl_br_7,pdsch_out_loop_adj_dl_br_8," +
            "pdsch_out_loop_adj_dl_br_9,pdsch_out_loop_adj_dl_br_10,pdsch_out_loop_adj_dl_br_11," +
            "pusch_out_loop_adj_dl_br_0,pusch_out_loop_adj_dl_br_1,pusch_out_loop_adj_dl_br_2," +
            "pusch_out_loop_adj_dl_br_3,pusch_out_loop_adj_dl_br_4,pusch_out_loop_adj_dl_br_5," +
            "pusch_out_loop_adj_dl_br_6,pusch_out_loop_adj_dl_br_7,pusch_out_loop_adj_dl_br_8," +
            "pusch_out_loop_adj_dl_br_9,pusch_out_loop_adj_dl_br_10,pusch_out_loop_adj_dl_br_11" +
            "rank_tx_14,rank_tx_15," +
            "sinr_meas_pdcch_0,sinr_meas_pdcch_1,sinr_meas_pdcch_2,sinr_meas_pdcch_3," +
            "sinr_meas_pdcch_4,sinr_meas_pdcch_5,sinr_meas_pdcch_6,sinr_meas_pdcch_7," +
            "sinr_meas_pdcch_8,sinr_meas_pdcch_9,sinr_meas_pdcch_10,sinr_meas_pdcch_11," +
            "sinr_meas_pusch_extend_0,sinr_meas_pusch_extend_1,sinr_meas_pusch_extend_2," +
            "sinr_meas_pusch_extend_3,sinr_meas_pusch_extend_4,sinr_meas_pusch_extend_5," +
            "sinr_meas_pusch_extend_6,sinr_meas_pusch_extend_7,sinr_meas_pusch_extend_8," +
            "sinr_meas_pusch_extend_9,sinr_meas_pusch_extend_10,sinr_meas_pusch_extend_11," +
            "dtvm_dtx_ind,utvm_dtx_ind";

    public static final String EVENT_HEADER_3076_UE_TRAFFIC = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisecond," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionRef," +
            "perUeThpPdcpvolTrunkDl,perUeThpTimeDl," +
            "perUeThpPdcpvolTrunkUl,perUeThpTimeUl," +
            "perSchedActivityUeUl,perSchedActivityUeDl," +
            "perUePdcpSrbAckvolDl,perUePdcpSrbTransvolDl,perUePdcpSrbRecvolUl," +
            "perUeRlcAckDl,perUeRlcNackDl,perUeRlcAckUl,perUeRlcNackUl," +
            "perUeDlMacDelay," +
            "perUeHarqDlAckQpsk,perUeHarqDlNackQpsk,perUeHarqUlSuccQpsk," +
            "ueHarqUlFailQpsk,ueHarqDlAck16qam,ueHarqDlNack16qam," +
            "ueHarqUlSucc16qam,ueHarqUlFail16qam,ueHarqDlAck64qam,ueHarqDlNack64qam," +
            "perUeMacDtxUlQpsk,perUeMacDtxDlQpsk,perUeMacDtxDl16qam," +
            "perUeMacDtxUl16qam,perUeMacDtxDl64qam," +
            "radiothpVolDl,radiothpResDl,radiothpVolUl,radiothpResUl," +
            "perUeThpDlDrb,perUeThpUlDrb," +
            "pdcpSduVoipUlpdbOk," +
            "perUeRateShapeTimeUl,perUeRlcPollRetxDl,perUeRlcPollRetxUl," +
            "ueHarqDlAck256qam,ueHarqDlNack256qam," +
            "perUeMacDtxDl256qam," +
            "perUeThpMactimeDrbDl,perUeThpMacvolDrbDl,perUeThpMacDrbDl,perUeThpMacvolUl," +
            "perUeThpMactimeUl,perUeThpMacUl," +
            "ueHarqUlSucc64qam,ueHarqUlFail64qam," +
            "perUeMacDtxUl64qam,plmnIndex,ueCategoryFlex,spidValue," +
            "ueHarqDlAckBpsk,ueHarqDlNackBpsk," +
            "dlharqAnmodeUsedFormat30,dlharqAnmodeUsedFormat31,dlharqAnmodeUsedFormat32," +
            "dlharqAnmodeUsedFormat33," +
            "dlharqAnmodeUsedMux0,dlharqAnmodeUsedMux1,dlharqAnmodeUsedMux2," +
            "dlharqAnmodeUsedMux3," +
            "format3ResCollision,uePowerClass,brCeLevel," +
            "ueVoipQualityUlOk,ueVoipQualityUlNok," +
            "subscriberGroupId," +
            "perSchedActivityUeUlShortsps,perUeThpTimeUlInitial,perUeThpPdcpvolTrunkUlInitial," +
            "ueEndcStage," +
            "perUeMacDtxUl256qam,ueHarqUlFail256qam,ueHarqUlSucc256qam," +
            "perUeMacDtxUlSkipulpreschd,perUeMacDtxUlSkipultxsps,perUeMacDtxUlSkipuldyn," +
            "ueHarqIuaUlFailQpsk,ueHarqIuaUlFail16qam," +
            "perUeMacUlUnresUePucchSrGrantSamp," +
            "perUeMacVolUlResUe,perUeMacTimeUlResUe," +
            "perUeMacVolUlResUeLastTti,perUeMacTimeUlResUeLastTtiSamp," +
            "perUeMacVolUlResUeLate,perUeMacTimeUlResUeLate," +
            "perUlHeavyUeThpBeforeHo,perUlHeavyUeThpAfterHo," +
            "perUlHeavyUeRequiredTbsBeforeHo,perUlHeavyUeRequiredTbsAfterHo," +
            "perUeMacUlUnresUePreemptGrantSamp,perUeMacUlUnresUeBsrGrantSamp," +
            "perUeMacDtxUlSkipulpreschdVolte,perUeMacDtxUlSkipuldynVolte," +
            "perUlHeavyUeRequiredTbsBeforeHoSele,perUlHeavyUeRequiredTbsAfterHoSele," +
            "perUlHeavyUePcellThpBeforeHoSele,perUlHeavyUePcellThpAfterHoSele," +
            "perUlScellActivityStateBeforeSele,perUlScellActivityStateAfterSele," +
            "perUlScellThpBeforeSele,perUlScellThpAfterSele," +
            "ueHarqUlTrans1,ueHarqUlTrans2,ueHarqUlTrans3,ueHarqUlTrans4," +
            "ueHarqUlTrans5,ueHarqUlTrans6,ueHarqUlTrans7," +
            "ueHarqUlAllDtx," +
            "ueHarqDlTrans1,ueHarqDlTrans2,ueHarqDlTrans3,ueHarqDlTrans4," +
            "ueHarqDlTrans5,ueHarqDlTrans6,ueHarqDlTrans7," +
            "ueHarqDlAllDtx," +
            "perUeMacVolUlUnresUePucchSrGrant,perUeMacVolUlUnresUePreemptGrant," +
            "perUeMacVolUlUnresUeBsrGrant," +
            "perUeThpPdcptimeDrbDl,perSchedActivityUeUlcomp";

    public static final String EVENT_HEADER_3114_MDT3 = "Datetime,Within_Start_&_End_Time,timestamp_hour,timestamp_minute,timestamp_second,timestamp_millisec," +
            "scanner_id,rbs_module_id,global_cell_id," +
            "mdt_m3_noiseinterf_meas0,mdt_m3_noiseinterf_meas1,mdt_m3_noiseinterf_meas2," +
            "mdt_m3_noiseinterf_meas3,mdt_m3_noiseinterf_meas4,mdt_m3_noiseinterf_meas5," +
            "mdt_m3_noiseinterf_meas6,mdt_m3_noiseinterf_meas7,mdt_m3_noiseinterf_meas8," +
            "mdt_m3_noiseinterf_meas9,mdt_m3_noiseinterf_meas10,mdt_m3_noiseinterf_meas11," +
            "mdt_m3_noiseinterf_meas12,mdt_m3_noiseinterf_meas13,mdt_m3_noiseinterf_meas14," +
            "mdt_m3_noiseinterf_meas15";

    public static final String EVENT_HEADER_3116_MDT5 = "Datetime,Within_Start_&_End_Time,timestamp_hour,timestamp_minute,timestamp_second,timestamp_millisecond," +
            "scanner_id,rbs_module_id,global_cell_id,enbs1apid,mmes1apid,gummei," +
            "rac_ue_ref,trace_recording_session_ref," +
            "mdt_m5_ue_thp_time_ul,mdt_m5_ue_thp_vol_ul," +
            "mdt_m5_erab_thp_time_dl_0,mdt_m5_erab_thp_time_dl_1,mdt_m5_erab_thp_time_dl_2," +
            "mdt_m5_erab_thp_time_dl_3,mdt_m5_erab_thp_time_dl_4,mdt_m5_erab_thp_time_dl_5," +
            "mdt_m5_erab_thp_time_dl_6,mdt_m5_erab_thp_time_dl_7,mdt_m5_erab_thp_time_dl_8," +
            "mdt_m5_erab_thp_time_dl_9,mdt_m5_erab_thp_time_dl_10,mdt_m5_erab_thp_time_dl_11," +
            "mdt_m5_erab_thp_time_dl_12,mdt_m5_erab_thp_time_dl_13,mdt_m5_erab_thp_time_dl_14," +
            "mdt_m5_erab_thp_time_dl_15," +
            "mdt_m5_erab_thp_vol_dl_0,mdt_m5_erab_thp_vol_dl_1,mdt_m5_erab_thp_vol_dl_2," +
            "mdt_m5_erab_thp_vol_dl_3,mdt_m5_erab_thp_vol_dl_4,mdt_m5_erab_thp_vol_dl_5," +
            "mdt_m5_erab_thp_vol_dl_6,mdt_m5_erab_thp_vol_dl_7,mdt_m5_erab_thp_vol_dl_8," +
            "mdt_m5_erab_thp_vol_dl_9,mdt_m5_erab_thp_vol_dl_10,mdt_m5_erab_thp_vol_dl_11," +
            "mdt_m5_erab_thp_vol_dl_12,mdt_m5_erab_thp_vol_dl_13,mdt_m5_erab_thp_vol_dl_14," +
            "mdt_m5_erab_thp_vol_dl_15," +
            "erab_qci_0,erab_qci_1,erab_qci_2,erab_qci_3,erab_qci_4,erab_qci_5,erab_qci_6,erab_qci_7," +
            "erab_qci_8,erab_qci_9,erab_qci_10,erab_qci_11,erab_qci_12,erab_qci_13,erab_qci_14," +
            "erab_qci_15," +
            "mdt_m5_ue_thp_time_dl,mdt_m5_ue_thp_vol_dl,mdt_m5_ue_lasttti_vol_dl";

    public static final String EVENT_HEADER_3112_LOC = "Datetime,Within_Start_&_End_Time,timestampHour,timestampMinute,timestampSecond,timestampMillisecond," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionRef," +
            "affectedMeasType,rsrpServing,rsrqServing," +
            "physicalCellId1,rsrpResult1,rsrqResult1," +
            "physicalCellId2,rsrpResult2,rsrqResult2," +
            "physicalCellId3,rsrpResult3,rsrqResult3," +
            "physicalCellId4,rsrpResult4,rsrqResult4," +
            "physicalCellId5,rsrpResult5,rsrqResult5," +
            "physicalCellId6,rsrpResult6,rsrqResult6," +
            "physicalCellId7,rsrpResult7,rsrqResult7," +
            "physicalCellId8,rsrpResult8,rsrqResult8," +
            "mdt_m1_location_coordinates," +
            "mdt_m1_ellipsoid_point_latitude_sign,mdt_m1_ellipsoid_point_degrees_latitude," +
            "mdt_m1_ellipsoid_point_degrees_longitude," +
            "mdt_m1_ellipsoid_point_with_alti_latitude_sign," +
            "mdt_m1_ellipsoid_point_with_alti_degrees_latitude," +
            "mdt_m1_ellipsoid_point_with_alti_degrees_longitude," +
            "mdt_m1_ellipsoid_point_with_alti_altitude_direction," +
            "mdt_m1_ellipsoid_point_with_alti_altitude," +
            "mdt_m1_ellipsoid_point_with_uncer_circle_latitude_sign," +
            "mdt_m1_ellipsoid_point_with_uncer_circle_degrees_latitude," +
            "mdt_m1_ellipsoid_point_with_uncer_circle_degrees_longitude," +
            "mdt_m1_ellipsoid_point_with_uncer_circle_uncertainty," +
            "mdt_m1_ellipsoid_point_with_uncer_ellipse_latitude_sign," +
            "mdt_m1_ellipsoid_point_with_uncer_ellipse_degrees_latitude," +
            "mdt_m1_ellipsoid_point_with_uncer_ellipse_degrees_longitude," +
            "mdt_m1_ellipsoid_point_with_uncer_ellipse_uncertainty_semi_major," +
            "mdt_m1_ellipsoid_point_with_uncer_ellipse_uncertainty_semi_minor," +
            "mdt_m1_ellipsoid_point_with_uncer_ellipse_orientaion_major_axis," +
            "mdt_m1_ellipsoid_point_with_uncer_ellipse_confidence," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_latitude_sign," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_degrees_latitude," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_degrees_longitude," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_altitude_direction," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_altitude," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_uncertainty_semi_major," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_uncertainty_semi_minor," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_orientaion_major_axis," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_uncertainty_altitude," +
            "mdt_m1_ellipsoid_point_with_alti_and_uncer_ellipsoid_confidence," +
            "mdt_m1_ellipsoid_arc_latitude_sign," +
            "mdt_m1_ellipsoid_arc_degrees_latitude," +
            "mdt_m1_ellipsoid_arc_degrees_longitude," +
            "mdt_m1_ellipsoid_arc_inner_radius," +
            "mdt_m1_ellipsoid_arc_uncertainty_radius," +
            "mdt_m1_ellipsoid_arc_offset_angle," +
            "mdt_m1_ellipsoid_arc_included_angle," +
            "mdt_m1_ellipsoid_arc_confidence," +
            "mdt_m1_polygon1_latitude_sign,mdt_m1_polygon1_degrees_latitude," +
            "mdt_m1_polygon1_degrees_longitude," +
            "mdt_m1_polygon2_latitude_sign,mdt_m1_polygon2_degrees_latitude," +
            "mdt_m1_polygon2_degrees_longitude," +
            "mdt_m1_polygon3_latitude_sign,mdt_m1_polygon3_degrees_latitude," +
            "mdt_m1_polygon3_degrees_longitude," +
            "mdt_m1_polygon4_latitude_sign,mdt_m1_polygon4_degrees_latitude," +
            "mdt_m1_polygon4_degrees_longitude," +
            "mdt_m1_polygon5_latitude_sign,mdt_m1_polygon5_degrees_latitude," +
            "mdt_m1_polygon5_degrees_longitude," +
            "mdt_m1_polygon6_latitude_sign,mdt_m1_polygon6_degrees_latitude," +
            "mdt_m1_polygon6_degrees_longitude," +
            "mdt_m1_polygon7_latitude_sign,mdt_m1_polygon7_degrees_latitude," +
            "mdt_m1_polygon7_degrees_longitude," +
            "mdt_m1_horizontal_velocity_bearing,mdt_m1_horizontal_velocity_horizontal_speed," +
            "paramMdtM1GnssTodMsec," +
            "mdtM1Frequency";

    public static final String EVENT_HEADER_3108_TA = "timestampHour,timestampMinute,timestampSecond,timestampMillisecond," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionRef," +
            "startTimestampHour,startTimestampMinute,startTimestampSecond,startTimestampMillisecond," +
            "taInterval," +
            "ta0,ta1,ta2,ta3,ta4,ta5,ta6,ta7,ta8,ta9,ta10,ta11,ta12,ta13,ta14,ta15,ta16,ta17,ta18,ta19," +
            "ta20,ta21,ta22,ta23,ta24,ta25,ta26,ta27,ta28,ta29,ta30,ta31,ta32,ta33,ta34,ta35,ta36," +
            "ta37,ta38,ta39,ta40,ta41,ta42,ta43,ta44,ta45,ta46,ta47,ta48,ta49,ta50,ta51,ta52," +
            "ta53,ta54,ta55,ta56,ta57,ta58,ta59";

    public static final String EVENT_HEADER_3115_ERAB = "timestampHour,timestampMinute,timestampSecond,timestampMillisecond," +
            "scannerId,rbsModuleId,globalCellId,enbs1apid,mmes1apid,gummei," +
            "racUeRef,traceRecordingSessionRef," +
            "mdtM4ErabPdcpVolUl_0," +
            "mdtM4ErabPdcpVolUl_1," +
            "mdtM4ErabPdcpVolUl_2," +
            "mdtM4ErabPdcpVolUl_3," +
            "mdtM4ErabPdcpVolUl_4," +
            "mdtM4ErabPdcpVolUl_5," +
            "mdtM4ErabPdcpVolUl_6," +
            "mdtM4ErabPdcpVolUl_7," +
            "mdtM4ErabPdcpVolUl_8," +
            "mdtM4ErabPdcpVolUl_9," +
            "mdtM4ErabPdcpVolUl_10," +
            "mdtM4ErabPdcpVolUl_11," +
            "mdtM4ErabPdcpVolUl_12," +
            "mdtM4ErabPdcpVolUl_13," +
            "mdtM4ErabPdcpVolUl_14," +
            "mdtM4ErabPdcpVolUl_15," +
            "mdtM4ErabPdcpVolDl_0,mdtM4ErabPdcpVolDl_1,mdtM4ErabPdcpVolDl_2,mdtM4ErabPdcpVolDl_3," +
            "mdtM4ErabPdcpVolDl_4,mdtM4ErabPdcpVolDl_5,mdtM4ErabPdcpVolDl_6,mdtM4ErabPdcpVolDl_7," +
            "mdtM4ErabPdcpVolDl_8,mdtM4ErabPdcpVolDl_9,mdtM4ErabPdcpVolDl_10," +
            "mdtM4ErabPdcpVolDl_11,mdtM4ErabPdcpVolDl_12,mdtM4ErabPdcpVolDl_13," +
            "mdtM4ErabPdcpVolDl_14,mdtM4ErabPdcpVolDl_15," +
            "mdtM4M5ErabQci_0,mdtM4M5ErabQci_1,mdtM4M5ErabQci_2,mdtM4M5ErabQci_3," +
            "mdtM4M5ErabQci_4,mdtM4M5ErabQci_5,mdtM4M5ErabQci_6,mdtM4M5ErabQci_7," +
            "mdtM4M5ErabQci_8,mdtM4M5ErabQci_9,mdtM4M5ErabQci_10,mdtM4M5ErabQci_11," +
            "mdtM4M5ErabQci_12,mdtM4M5ErabQci_13,mdtM4M5ErabQci_14,mdtM4M5ErabQci_15";

    public static final String EVENT_HEADER_5G_COMMON_HEADER = "time_stamp," +
            "system_uuid," +
            "compute_name," +
            "network_managed_element," +
            "pm_event_job_ids," +
            "trace_reference," +
            "trace_recording_session_reference,";

    public static final String EVENT_HEADER_3349_CU_CP_PER_UE_PUEM_ENDC_REPORT = EVENT_HEADER_5G_COMMON_HEADER +
            "main_plmn_id,gnb_id,gnb_id_length," +
            "global_gnb_plmn_identity,global_gnb_id," +
            "nci,serving_plmn_id," +
            "pcell_ecgi_plmn_id,pcell_ecgi_cell_id," +
            "pref_ue_group_id,ue_group_id,ue_mobility_group_id," +
            "ue_service_group_id,ue_admission_group_id," +
            "measured_frequency,measured_frequency_subcarrier_spacing,measurement_count," +
            "meas_result_ps_cell_phys_cell_id," +
            "meas_result_ps_cell_ssb_cell_rsrp," +
            "meas_result_ps_cell_ssb_cell_rsrq," +
            "meas_result_ps_cell_ssb_cell_sinr," +
            "meas_result_ps_cell_rs_index_results,"+
            "meas_result_serving_mo_list," +
            "meas_result_neigh_cells_nr_list";


    public static final String EVENT_HEADER_3231_CU_CP_PER_UE_MDT_M6_UL_REPORT = EVENT_HEADER_5G_COMMON_HEADER +
            "main_plmn_id,gnb_id,nci,gnb_id_length," +
            "global_gnb_plmn_identity,global_gnb_id," +
            "mdt_m6_ul_packet_delay_measurement_list," +
            "menb_id_plmn_id,menb_id_enb_id," +
            "menb_cell_id,serving_plmn_id,nr_type";

    public static final String EVENT_HEADER_3230_CU_CP_PER_UE_MDT_REPORT = EVENT_HEADER_5G_COMMON_HEADER +
            "main_plmn_id,gnb_id," +
            "asn1_msg_direction, asn1_msg_content, asn1_protocol_names," +
            "nci,gnb_id_length," +
            "global_gnb_plmn_id,global_gnb_id," +
            "report_type,triggering_event," +
            "menb_plmn_id,menb_enb_id," +
            "menb_cell_id,serving_plmn_id," +
            "measured_frequency,nr_type,measured_frequency_subcarrier_spacing";
}
